### ISSUE TITLE
When deploying using traefik I get a forbidden error

### ISSUE THREAD

**Issue by trajano** [moodlehq/moodle-php-apache#76]
I have my service as 
```
  moodle:
    image: moodlehq/moodle-php-apache:7.1

      labels:
        - "traefik.main.frontend.rule=Host:moodle.XXX.com"
        - "traefik.main.frontend.whiteList.useXForwardedFor=true"
        - "traefik.main.port=80"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
```
just to test it out, but I get 
![image](https://user-images.githubusercontent.com/110627/62584684-9b76ee00-b883-11e9-9b4a-06725c14b535.png)
